### ISSUE TITLE
Implement subtract using add

### ISSUE THREAD

**Issue by dpsanders** [JeffreySarnoff/ErrorfreeArithmetic.jl#1]
subtract(a, b) = add(a, - b) 
can replace all of the subtract methods, I believe.

**Comment by JeffreySarnoff** [comment]
It could, but either the errorfree assurance needs the implementation given, or --more likely-- this way is faster (as I recall)

**Comment by JeffreySarnoff** [comment]
Yes -- the current implementation saves a few cycles
