### ISSUE TITLE
multiply_errorfree seems to have disappeared

### ISSUE THREAD

**Issue by dpsanders** [JeffreySarnoff/ErrorfreeArithmetic.jl#10]
This is used by IntervalArithmetic.jl.

**Comment by JeffreySarnoff** [comment]
The new interface is better.  Here is what you need for compatibility with the former exports,

```julia
using ErrorfreeArithmetic

@inline add_errorfree(a::T, b::T) where {T<:Base.IEEEFloat} = two_sum(a, b)
@inline subtract_errorfree(a::T, b::T) where {T<:Base.IEEEFloat} = two_diff(a, b)
@inline multiply_errorfree(a::T, b::T) where {T<:Base.IEEEFloat} = two_prod(a, b)
@inline square_errorfree(a::T) where {T<:Base.IEEEFloat} = two_square(a)
```

**Comment by dpsanders** [comment]
If the new interface is better, then let's use that.
I have just realised that these functions are not used directly in IntervalArithmetic.jl at all, but rather via FastRounding.jl. Sorry for the confusion.
