### ISSUE TITLE
Duplicate functions

### ISSUE THREAD

**Issue by schillic** [JeffreySarnoff/ErrorfreeArithmetic.jl#12]
In 937b4ca there came new functions `three_hilo_sum` ([here](https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl/commit/937b4ca6744a5893ccc6678cfeab7d6608a6a6bb#diff-4aba30db5d89f0136c88332060d22b97R201) and [here](https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl/commit/937b4ca6744a5893ccc6678cfeab7d6608a6a6bb#diff-4aba30db5d89f0136c88332060d22b97R216)) and `three_hilo_diff` ([here](https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl/commit/937b4ca6744a5893ccc6678cfeab7d6608a6a6bb#diff-4aba30db5d89f0136c88332060d22b97R231) and [here](https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl/commit/937b4ca6744a5893ccc6678cfeab7d6608a6a6bb#diff-4aba30db5d89f0136c88332060d22b97R246)), each with two methods with identical signature. The compiler overwrites the first method and warns about that. The documentation indicates that the respective second method should have a different name (`three_lohi_sum` and `three_lohi_diff`). Without knowing the details, this looks like a bug.

**Comment by JeffreySarnoff** [comment]
Thank you.  It was an editing oversight. I had the correct names in the doc strings only.  The "dups" are the `_lohi_` versions of the `_hilo_` functions.  Fixed and tagged new release.  Very Helpful.
