### ISSUE TITLE
exact remainder

### ISSUE THREAD

**Issue by nestordemeure** [JeffreySarnoff/ErrorfreeArithmetic.jl#15]
Would you be interested in a pull request adding the exact remainder for the sqrt and division ?

They are easy to implement (using an fma) and ErrorfreeArithmetic.jl seem like the proper place to put them.

**Comment by JeffreySarnoff** [comment]
Thank you for the interest: `two_inv`, `two_div` , `two_sqrt` are exported.  The implementations are in https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl/blob/master/src/leasterror.jl because the results are not strictly errorfree in the way that `two_sum` and the others are (they are very nearly so, all are very good).  The intro page lists all exports https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl

**Comment by nestordemeure** [comment]
I saw them but, if I am not mistaken, they give the result and the error (such that `result+error=true result`) and not the _remainder_ (such that `(x+rem)/y = result`).

**Comment by JeffreySarnoff** [comment]
Yes, I had misread your note.  The PR proposal probably makes sense -- is the exact remainder given as 1(hi_part = Float64(true_exact_remainder), lo_part = Float64(error_in(hi_part)))` ?

`x_over_y_hi, x_over_y_lo = two_div(x,  y)`
`x_over_y_accurate = widen(x_over_y_hi) + widen(x_over_y_lo)`
Please show me how to characterize the "exact remainder" for `/` and `sqrt` similarly.

What about a corresponding relative error for addition, subtraction, multiplication?

**Comment by nestordemeure** [comment]
The implementation would be something like : 

```Julia
# (x+remainder) / y = result
function rem_div(x, y)
   result = x / y
   remainder = fma(y, result, -x)
   (result, remainder)
end

# sqrt(x+remainder) = result
function rem_sqrt(x)
   result = sqrt(x)
   remainder = fma(result, result, -x)
   (result, remainder)
end
```

Those particular operations are exact and useful for some algorithms (I personally use them but the most famous example is the use of the sqrt remainder inside a newton iteration to improve an approximation of the sqrt) but I am not aware of any use for corresponding addition/substraction/multiplication operations.

**Comment by JeffreySarnoff** [comment]
How do you use `rem_div`?

**Comment by nestordemeure** [comment]
I use it to implement division for something similar to quad numbers.

**Comment by JeffreySarnoff** [comment]
I like your suggestion.  I have added `src/remainder.jl` and export `div_rem, sqrt_rem` in the current master. PR away in a new branch.

**Comment by nestordemeure** [comment]
Great, I will do it this weekend.

**Comment by nestordemeure** [comment]
I just pushed the PR (the formula is the opposite of the one given above to stay consistent with the literature).
