### ISSUE TITLE
Use modules 

### ISSUE THREAD

**Issue by dpsanders** [JeffreySarnoff/ErrorfreeArithmetic.jl#2]

**Comment by dpsanders** [comment]
I wonder if it makes any sense to have a submodule ErrorFree and a submodule Accurate to be able to write 

ErrorFree.add(a, b) 

Or even 

ErrorFree.:+(a, b) 

Alternatively use a trait to write eg 

+(ErrorFree, a, b) 

Where ErrorFree is an instance in the same way as  RoundUp

**Comment by JeffreySarnoff** [comment]
there are other clients for ErrorfreeArithmetic

**Comment by JeffreySarnoff** [comment]
when we have traits as part of the language --- 
This is designed to work well for FastRounding.jl 
(I need it registered before registering FastRounding, so let's get there first; then, as appropriate, rethink)

**Comment by JeffreySarnoff** [comment]
AdjacentFloats and ErrorfreeArithmetic have more clients and so need standard decoupled design.
I am closing this to continue cleanly -- we can revisit the larger question when the tools are registered.
